### PR TITLE
Support stage & watch CLI parameters

### PR DESCRIPTION
**Pull request by iamdavidmartin**
Currently this plugin can only run using the dev stage because that's the default stage. However, in my case I need to specify the stage I want to run.

I updated the README with the third "stage" parameter supported, but there are a lot changes that are just formatting because I automatically run prettier on save of my Javascript files. Hope that's not an issue.

This plugin is super helpful. Thanks for making it!

### CODE REVIEW

**Comment by isitgeorge** [comment]
Hi @iamdavidmartin,

Thanks for your contribution, it looks good! Glad to hear its useful

**Comment by iamdavidmartin** [comment]
Glad you like it.

I just committed another set of changes. I needed to enable/disable nodemon per service, so I've added yet another CLI argument called `watch` to support that.

I also re-wrote the way the args are read from the command line to catch more mistakes users may enter, and allow more flexibility for future additional args in a way that is quite a departure from your original implementation. It's good and bad. The promise nesting of your implementation is gone and I replaced it with code that is in some ways less readable. I commented it in hopes that it makes sense.

**Comment by isitgeorge** [comment]
No problem, I'm a bit busy at the moment but will review soon! Have you finished the change?

Cheers

**Comment by iamdavidmartin** [comment]
Oh, good question. I'm finished for now. It's possible I could come across other things but I'm satisfied with it now.

**Comment by isitgeorge** [comment]
Awesome, I'll get this tested and release this week!

**Comment by isitgeorge** [comment]
Apologies for the massive delay. I'm going to be tweaking this and finally merging it back in over the next few days, hope you don't mind!

**Comment by iamdavidmartin** [comment]
That's ok. I've moved on to using serverless-stack instead of the serverless framework. Allows for true local lambda debugging which is what my goal was using this project (and others).

**Pull request merged**
