### PR TITLE
feat(cli): add support to httpPort and lambdaPort & more colours

### PR DESCRIPTION
**Pull request by rodrigopasc**
As reported in https://github.com/isitgeorge/serverless-offline-multi/issues/3 I added support to the `serverless-offline` _lambdaPort_ problem.

### CODE REVIEW

**Comment by isitgeorge** [comment]
Looks good! Could you maybe add a line into the readme so that anybody using lambdaPort knows which port to expect (+1000).

Cheers

**Comment by rodrigopasc** [comment]
Hi @isitgeorge. I hope you're okay! :D 

I'm sorry for the delayed answer. I didn't get the notification :( 

Anyway, I just commited (as seen in https://github.com/isitgeorge/serverless-offline-multi/pull/4/commits/9fc6a91d36a98acffe245216355b07090475f48d) the new README.

Do you have any suggestion?

Thank you.

**Comment by rodrigopasc** [comment]
@isitgeorge Hey, how are you?

Any updates on this?

Thank you.

**Comment by isitgeorge** [comment]
@rodrigopasc sorry for delay! GitHub notifications aren't the best!

Thanks for the contribution, releasing now.

**Comment by isitgeorge** [comment]
Apologies for the delay, this is available in NPM now!

**Pull request merged**
